import React, { useEffect, useState } from 'react'
import { Alert, Button, Card, Descriptions, Form, Input, Space, Spin, Tag, Typography } from 'antd'
import { requestJSON } from './api.js'

export default function AccountCenterPage({ user, onLogout, mode = 'profile' }) {
  const [state, setState] = useState({ loading: true, saving: false, error: '', data: null })
  const [form] = Form.useForm()
  const endpoint = mode === 'member' ? '/api/v1/member-center' : '/api/v1/account/profile'
  const load = async () => { setState(v => ({ ...v, loading: true, error: '' })); try { const data = await requestJSON(endpoint); form.setFieldsValue({ displayName: data?.profile?.displayName || '' }); setState({ loading: false, saving: false, error: '', data }) } catch (error) { setState(v => ({ ...v, loading: false, error: error.message || '读取账户资料失败' })) } }
  useEffect(() => { void load() }, [endpoint])
  const save = async () => { try { const value = await form.validateFields(); setState(v => ({ ...v, saving: true, error: '' })); const data = await requestJSON('/api/v1/account/profile', { method: 'PUT', body: JSON.stringify(value) }); setState({ loading: false, saving: false, error: '', data }) } catch (error) { if (!error?.errorFields) setState(v => ({ ...v, saving: false, error: error.message || '保存失败' })) } }
  const data = state.data || {}; const profile = data.profile || {}; const membership = data.membership || { capabilities: [] }
  return <main className="account-center-page"><section className="account-center-heading"><div><Typography.Text type="secondary">一战晟铭 · 服务端账户事实</Typography.Text><Typography.Title level={2}>{mode === 'member' ? '会员与权限' : '个人资料'}</Typography.Title><Typography.Paragraph type="secondary">不展示密码、Cookie、Session、MFA 密钥、恢复码或访问密钥。</Typography.Paragraph></div><Button danger onClick={() => void onLogout?.()} loading={state.saving}>退出登录</Button></section>{state.error && <Alert type="error" showIcon message={state.error} style={{ marginBottom: 16 }} />}{state.loading ? <Spin /> : <><Card title="账号与团队身份"><Descriptions column={{ xs: 1, sm: 2 }} bordered><Descriptions.Item label="显示名称">{profile.displayName || '未设置'}</Descriptions.Item><Descriptions.Item label="用户名">{profile.username || '未设置'}</Descriptions.Item><Descriptions.Item label="角色"><Tag color="blue">{String(membership.role || 'member').toUpperCase()}</Tag></Descriptions.Item><Descriptions.Item label="团队">{membership.teamId ? `团队 #${membership.teamId}` : '尚未加入团队'}</Descriptions.Item><Descriptions.Item label="邮箱验证">{data.security?.emailVerification === 'verified' ? '已验证' : '不可用'}</Descriptions.Item><Descriptions.Item label="MFA">{data.security?.mfa === 'enabled' ? '已启用' : '不可用'}</Descriptions.Item></Descriptions></Card>{mode === 'profile' && <Card title="编辑资料" style={{ marginTop: 16 }}><Form form={form} layout="inline"><Form.Item name="displayName" label="显示名称" rules={[{ required: true, max: 64 }]}><Input aria-label="显示名称" /></Form.Item><Button type="primary" onClick={() => void save()} loading={state.saving}>保存资料</Button></Form><Typography.Paragraph type="secondary" style={{ marginTop: 12 }}>头像上传在受控 TOS 存储未配置前保持不可用，不接受浏览器直传或任意地址。</Typography.Paragraph></Card>}<Card title="当前已生效能力" style={{ marginTop: 16 }}>{membership.capabilities?.length ? <Space wrap>{membership.capabilities.map(capability => <Tag key={capability} color="geekblue">{capability}</Tag>)}</Space> : <Typography.Text type="secondary">没有可展示的独立能力。</Typography.Text>}</Card>{mode === 'member' && <Card title="用量、活动与通知" style={{ marginTop: 16 }}><Typography.Text type="secondary">当前没有可授权的 MySQL 投影时显示不可用，不会由浏览器生成统计。</Typography.Text></Card>}</>}</main>
}
