import React,{useEffect,useMemo,useState}from'react'
import {Alert,Button,Card,Empty,Input,List,Space,Spin,Typography}from'antd'
import {createAgentProject,continueAgentProject,deleteAgentProject,listAgentProjects}from'./api.js'
import './agent-studio.css'
export default function AgentStudioPage({onNavigate}){
 const[title,setTitle]=useState('');const[content,setContent]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[projects,setProjects]=useState([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState('')
 const refresh=async()=>{setLoading(true);try{const x=await listAgentProjects();setProjects(x.projects||[])}catch(e){setError(e.status===403?'无权限读取 Agent 项目。':(e.message||'读取项目失败'))}finally{setLoading(false)}};useEffect(()=>{void refresh()},[])
 const start=async()=>{setBusy(true);setError('');try{const created=await createAgentProject({title:title.trim()||'未命名创作'});const p=created.project;await continueAgentProject(p.id,{content});onNavigate(`/agent/canvas?projectId=${p.id}`)}catch(e){setError(e.code==='executor_unavailable'?'执行器未配置，项目已保存。':(e.message||'创建失败'))}finally{setBusy(false)}}
 const items=useMemo(()=>projects.filter(p=>(p.title||'').toLowerCase().includes(search.toLowerCase())),[projects,search])
 return <main className="agent-studio"><Card className="agent-hero"><Typography.Text className="agent-eyebrow">Agent Studio</Typography.Text><Typography.Title>开始创作</Typography.Title><Typography.Paragraph>描述创作需求，进入可恢复的专属画布。</Typography.Paragraph>{error&&<Alert type="error" message={error}/>}<Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="项目名称（可选）"/><Input.TextArea value={content} onChange={e=>setContent(e.target.value)} placeholder="描述你的创作需求…" autoSize={{minRows:6}}/><Space><Button type="primary" loading={busy} disabled={!content.trim()} onClick={()=>void start()}>开始创作</Button></Space></Card><Card title="最近项目" className="agent-projects" extra={<Input.Search aria-label="搜索项目" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索项目"/>}>{loading?<Spin/>:items.length===0?<Empty description="暂无 Agent 项目"/>:<List split={false} dataSource={items} renderItem={p=><List.Item><article className="agent-project-card" aria-label={`Agent 项目：${p.title||p.Title}`}><List.Item.Meta title={p.title||p.Title} description="服务端保存，可在重新登录后恢复"/><Space wrap><Button onClick={()=>onNavigate(`/agent/canvas?projectId=${p.id||p.ID}`)}>进入</Button><Button danger onClick={()=>void deleteAgentProject(p.id||p.ID).then(refresh).catch(e=>setError(e.message||'删除失败'))}>删除</Button></Space></article></List.Item>}/>}</Card></main>}
