import React, { useCallback, useEffect, useState } from 'react'
import { Alert, Button, Card, Empty, Input, Select, Space, Table, Typography } from 'antd'
import { listWorkspaceHistory } from './api.js'
import PageState from './ui/PageState.jsx'
import StatusTag from './ui/StatusTag.jsx'
import './tts-history.css'

export default function HistoryPage() {
  const [state, setState] = useState({ loading: true, refreshing: false, error: '', entries: [], page: 1, total: 0 })
  const [keyword, setKeyword] = useState(''); const [status, setStatus] = useState('')
  const load = useCallback(async (page = 1, refreshing = false) => { setState(v => ({ ...v, loading: !refreshing, refreshing, error: '' })); try { const data = await listWorkspaceHistory({ page, q: keyword, status }); setState({ loading: false, refreshing: false, error: '', entries: data.entries || [], page: data.page || page, total: data.total || 0 }) } catch (error) { setState(v => ({ ...v, loading: false, refreshing: false, error: error?.message || '读取项目历史失败' })) } }, [keyword, status])
  useEffect(() => { void load(1) }, [load])
  if (state.loading && !state.entries.length) return <PageState state="loading" title="正在读取项目历史…" className="tts-history-state" />
  if (state.error && !state.entries.length) return <PageState state="failed" title="项目历史读取失败" description={state.error} onRetry={() => void load()} className="tts-history-state" />
  return <main className="tts-history-page"><section className="tts-history-heading"><div><Typography.Text type="secondary">一战晟铭 · MySQL 用户范围投影</Typography.Text><Typography.Title level={2}>历史记录</Typography.Title><Typography.Paragraph type="secondary">仅展示当前账号有项目归属权限的项目与小说；搜索、状态筛选和分页均由服务端事实投影完成。</Typography.Paragraph></div><Button onClick={() => void load(1, true)} loading={state.refreshing}>刷新</Button></section>{state.error ? <Alert type="error" showIcon closable message={state.error} /> : null}<Card className="history-table-card"><Space wrap className="tts-history-controls"><Input.Search aria-label="搜索历史" placeholder="搜索项目、小说或 Book ID" value={keyword} onChange={e => setKeyword(e.target.value)} onSearch={() => void load(1)} allowClear /><Select aria-label="筛选历史状态" value={status} onChange={setStatus} options={[{ value: '', label: '全部状态' }, ...['pending','running','completed','failed','retryable_failed'].map(value => ({ value, label:value }))]} /></Space><Table rowKey="id" loading={state.refreshing} dataSource={state.entries} pagination={{ current: state.page, pageSize: 20, total: state.total, hideOnSinglePage: true, onChange: page => void load(page), showTotal: total => `共 ${total} 条` }} locale={{ emptyText: <Empty description="暂无可查看的项目历史" /> }} columns={[{ title:'项目 / 小说', render:(_,row)=><Space direction="vertical" size={0}><Typography.Text strong>{row.title || `小说 #${row.bookId}`}</Typography.Text><Typography.Text type="secondary">{row.projectName || `项目 #${row.projectId}`} · Book #{row.bookId}</Typography.Text></Space>},{title:'状态',dataIndex:'status',width:150,render:value=><StatusTag status={value}/>},{title:'最后更新',dataIndex:'updatedAt',width:210,render:value=>value ? new Date(value).toLocaleString('zh-CN',{hour12:false}) : '暂无执行记录'},{title:'操作',width:120,render:(_,row)=><Button size="small" href={`/shuihuo-production?projectId=${row.projectId}`}>打开项目</Button>}]}/></Card></main>
}
