-- +goose Up
CREATE TABLE agent_projects (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, owner_user_id BIGINT UNSIGNED NOT NULL, team_id BIGINT UNSIGNED NULL, title VARCHAR(191) NOT NULL, batch_project_id BIGINT NULL, book_id BIGINT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (id), KEY idx_agent_projects_owner (owner_user_id, updated_at), CONSTRAINT fk_agent_projects_owner FOREIGN KEY (owner_user_id) REFERENCES auth_users(id) ON DELETE CASCADE, CONSTRAINT fk_agent_projects_batch FOREIGN KEY (batch_project_id) REFERENCES batch_projects(id) ON DELETE SET NULL, CONSTRAINT fk_agent_projects_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE agent_messages (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, project_id BIGINT UNSIGNED NOT NULL, role VARCHAR(32) NOT NULL, content MEDIUMTEXT NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (id), KEY idx_agent_messages_project (project_id,id), CONSTRAINT fk_agent_messages_project FOREIGN KEY (project_id) REFERENCES agent_projects(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE agent_canvas_documents (project_id BIGINT UNSIGNED NOT NULL, revision INT NOT NULL DEFAULT 0, document_json JSON NOT NULL, updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (project_id), CONSTRAINT fk_agent_canvas_project FOREIGN KEY (project_id) REFERENCES agent_projects(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE agent_canvas_versions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, project_id BIGINT UNSIGNED NOT NULL, revision INT NOT NULL, document_json JSON NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (id), UNIQUE KEY uq_agent_canvas_version (project_id,revision), CONSTRAINT fk_agent_canvas_versions_project FOREIGN KEY (project_id) REFERENCES agent_projects(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE agent_attachments (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, project_id BIGINT UNSIGNED NOT NULL, owner_user_id BIGINT UNSIGNED NOT NULL, bucket VARCHAR(191) NOT NULL, object_key VARCHAR(512) NOT NULL, filename VARCHAR(255) NOT NULL, content_type VARCHAR(127) NOT NULL, byte_size BIGINT UNSIGNED NOT NULL, sha256 CHAR(64) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (id), KEY idx_agent_attachments_project (project_id,id), CONSTRAINT fk_agent_attachments_project FOREIGN KEY (project_id) REFERENCES agent_projects(id) ON DELETE CASCADE, CONSTRAINT fk_agent_attachments_owner FOREIGN KEY (owner_user_id) REFERENCES auth_users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE agent_executions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, project_id BIGINT UNSIGNED NOT NULL, status VARCHAR(32) NOT NULL, runtime_ref VARCHAR(191) NOT NULL DEFAULT '', error_code VARCHAR(64) NOT NULL DEFAULT '', error_message VARCHAR(512) NOT NULL DEFAULT '', created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (id), KEY idx_agent_executions_project (project_id,id), CONSTRAINT fk_agent_executions_project FOREIGN KEY (project_id) REFERENCES agent_projects(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE agent_skill_versions (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, owner_user_id BIGINT UNSIGNED NOT NULL, name VARCHAR(191) NOT NULL, version INT NOT NULL, body MEDIUMTEXT NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (id), UNIQUE KEY uq_agent_skill_version (owner_user_id,name,version), CONSTRAINT fk_agent_skills_owner FOREIGN KEY (owner_user_id) REFERENCES auth_users(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- +goose Down
DROP TABLE IF EXISTS agent_skill_versions; DROP TABLE IF EXISTS agent_executions; DROP TABLE IF EXISTS agent_attachments; DROP TABLE IF EXISTS agent_canvas_versions; DROP TABLE IF EXISTS agent_canvas_documents; DROP TABLE IF EXISTS agent_messages; DROP TABLE IF EXISTS agent_projects;
